const libraryLanguages = [
  { id: "yue", label: "粤语音乐剧" },
  { id: "en", label: "英语音乐剧" },
  { id: "de", label: "德语音乐剧" },
  { id: "fr", label: "法语音乐剧" },
];

const libraryShows = [
  {
    id: "dazhuangwang",
    deployed: true,
    language: "yue",
    cardClass: "dzw",
    href: "dazhuangwang/index.html",
    title: "大状王",
    image: "dazhuangwang/assets/show-logo.png",
    prefetch: ["dazhuangwang/songs.js"],
    coverLines: ["大状王"],
    originalTitle: "An impossible trial",
    meta: ["粤语", "粤拼", "注释"],
  },
  {
    id: "hamilton",
    deployed: true,
    language: "en",
    cardClass: "hamilton",
    href: "Hamilton/index.html",
    title: "Hamilton",
    image: "Hamilton/assets/Hamilton-Logo-1.svg",
    prefetch: ["Hamilton/lyrics-data.js"],
    meta: ["英语", "IPA", "中文对照"],
  },
  {
    id: "les-miserables",
    language: "en",
    cardClass: "lesmis",
    href: "les-miserables/index.html",
    title: "悲惨世界",
    image: "les-miserables/assets/show-logo.png",
    coverLines: ["悲惨", "世界"],
    originalTitle: "Les Misérables",
    meta: ["英语", "IPA", "中文对照"],
  },
  {
    id: "moulin-rouge",
    language: "en",
    cardClass: "moulin",
    href: "moulin-rouge/index.html",
    title: "红磨坊",
    image: "moulin-rouge/assets/show-logo.png",
    originalTitle: "Moulin Rouge! The Musical",
    meta: ["英语", "IPA", "中文对照"],
  },
  {
    id: "phantom-of-the-opera",
    language: "en",
    cardClass: "phantom",
    href: "phantom-of-the-opera/index.html",
    title: "剧院魅影",
    image: "phantom-of-the-opera/assets/show-logo.png",
    originalTitle: "The Phantom of the Opera",
    meta: ["英语", "IPA", "中文对照"],
  },
  {
    id: "love-never-dies",
    language: "en",
    cardClass: "love-never-dies",
    href: "love-never-dies/index.html",
    title: "真爱不死",
    image: "love-never-dies/assets/show-logo.png",
    originalTitle: "Love Never Dies",
    meta: ["英语", "IPA", "中文对照"],
  },
  {
    id: "elisabeth-das-musical",
    language: "de",
    cardClass: "elisabeth",
    href: "elisabeth-das-musical/index.html",
    title: "伊丽莎白",
    image: "elisabeth-das-musical/assets/show-logo.png",
    originalTitle: "Elisabeth",
    meta: ["德语", "IPA", "中英对照"],
  },
  {
    id: "mozart-das-musical",
    language: "de",
    cardClass: "mozart-musical",
    href: "mozart-das-musical/index.html",
    title: "莫扎特！",
    image: "mozart-das-musical/assets/show-logo.png",
    originalTitle: "Mozart! Das Musical",
    meta: ["德语", "IPA", "中英对照"],
  },
  {
    id: "rouge-et-noir",
    deployed: true,
    language: "fr",
    cardClass: "rouge",
    href: "rouge-et-noir/index.html",
    title: "摇滚红与黑",
    image: "rouge-et-noir/assets/show-logo.png",
    prefetch: ["rouge-et-noir/songs.js"],
    coverLines: ["摇滚", "红与黑"],
    originalTitle: "Le Rouge et le Noir",
    meta: ["法语", "IPA", "中英对照"],
  },
  {
    id: "starmania",
    language: "fr",
    cardClass: "starmania",
    href: "starmania/index.html",
    title: "星幻",
    image: "starmania/assets/show-logo.png",
    originalTitle: "Starmania",
    meta: ["法语", "IPA", "中英对照"],
  },
  {
    id: "les-souliers-rouges",
    language: "fr",
    cardClass: "souliers",
    href: "les-souliers-rouges/index.html",
    title: "红舞鞋",
    image: "les-souliers-rouges/assets/show-logo.png",
    originalTitle: "Les Souliers Rouges",
    meta: ["法语", "IPA", "中英对照"],
  },
  {
    id: "la-legende-du-roi-arthur",
    language: "fr",
    cardClass: "arthur",
    href: "la-legende-du-roi-arthur/index.html",
    title: "亚瑟王传奇",
    image: "la-legende-du-roi-arthur/assets/show-logo.png",
    originalTitle: "La Légende du Roi Arthur",
    meta: ["法语", "IPA", "中英对照"],
  },
  {
    id: "notre-dame-de-paris",
    language: "fr",
    cardClass: "ndp",
    href: "notre-dame-de-paris/index.html",
    title: "巴黎圣母院",
    image: "notre-dame-de-paris/assets/show-logo.png",
    coverLines: ["巴黎", "圣母院"],
    originalTitle: "Notre-Dame de Paris",
    meta: ["法语", "IPA", "中英对照"],
  },
  {
    id: "mozart-opera-rock",
    language: "fr",
    cardClass: "mozart",
    href: "mozart-opera-rock/index.html",
    title: "摇滚莫扎特",
    image: "mozart-opera-rock/assets/show-logo.png",
    coverLines: ["摇滚", "莫扎特"],
    originalTitle: "Mozart, l'opéra rock",
    meta: ["法语", "IPA", "中英对照"],
  },
  {
    id: "romeo-et-juliette",
    language: "fr",
    cardClass: "romeo",
    href: "romeo-et-juliette/index.html",
    title: "罗密欧与朱丽叶",
    image: "romeo-et-juliette/assets/show-logo.png",
    coverLines: ["罗密欧", "与朱丽叶"],
    originalTitle: "Roméo et Juliette",
    meta: ["法语", "IPA", "中英对照"],
  },
  {
    id: "le-roi-soleil",
    language: "fr",
    cardClass: "soleil",
    href: "le-roi-soleil/index.html",
    title: "太阳王",
    image: "le-roi-soleil/assets/show-logo.png",
    coverLines: ["太阳王"],
    originalTitle: "Le Roi Soleil",
    meta: ["法语", "IPA", "中英对照"],
  },
  {
    id: "1789-les-amants-de-la-bastille",
    language: "fr",
    cardClass: "bastille",
    href: "1789-les-amants-de-la-bastille/index.html",
    title: "1789：巴士底狱的恋人",
    image: "1789-les-amants-de-la-bastille/assets/show-logo.png",
    coverLines: ["1789"],
    originalTitle: "Les Amants de la Bastille",
    meta: ["法语", "IPA", "中英对照"],
  },
  {
    id: "don-juan",
    language: "fr",
    cardClass: "donjuan",
    href: "don-juan/index.html",
    title: "唐璜",
    image: "don-juan/assets/show-logo.png",
    coverLines: ["唐璜"],
    originalTitle: "Don Juan",
    meta: ["法语", "IPA", "中英对照"],
  },
  {
    id: "moliere-le-spectacle-musical",
    language: "fr",
    cardClass: "moliere",
    href: "moliere-le-spectacle-musical/index.html",
    title: "莫里哀",
    image: "moliere-le-spectacle-musical/assets/show-logo.png",
    coverLines: ["莫里哀"],
    originalTitle: "Molière",
    meta: ["法语", "IPA", "中英对照"],
  },
  {
    id: "cyrano-de-bergerac",
    language: "fr",
    cardClass: "cyrano",
    href: "cyrano-de-bergerac/index.html",
    title: "大鼻子情圣",
    image: "cyrano-de-bergerac/assets/show-logo.png",
    coverLines: ["大鼻子", "情圣"],
    originalTitle: "Cyrano de Bergerac",
    meta: ["法语", "IPA", "中英对照"],
  },
];

if (typeof window !== "undefined") {
  window.libraryLanguages = libraryLanguages;
  window.libraryShows = libraryShows;
}

if (typeof module !== "undefined") {
  module.exports = { libraryLanguages, libraryShows };
}
